import cv2 
import numpy as np
import os
from gst_cam import camera

# Camera matrix generated by `find_chessboard_corners.py`
mtx = np.array([[1.07975414e+03, 0.00000000e+00, 4.03079138e+02],
                [0.00000000e+00, 9.75039165e+02, 3.19767861e+02],
                [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])
dist = np.array([[-2.68066717e+00,  2.22829147e+01,  2.53538754e-02, -5.57868851e-02, -1.15847689e+02]])

w, h = 3280, 2464
cap = cv2.VideoCapture(camera(0, w, h))

while True :
    ret, frame = cap.read()
    if not ret :
        break

    frame = cv2.resize(frame, (0,0), fx=0.25, fy=0.25)
    h, w, c = frame.shape

    # refine the camera matrix based on a free scaling parameter using cv.getOptimalNewCameraMatrix().
    newcameramtx, roi = cv2.getOptimalNewCameraMatrix(mtx, dist, (w,h), 0, (w,h))

    # undistort using cv2.undistort()
    dst = cv2.undistort(frame, mtx, dist, None, newcameramtx)

    # crop the image
    x, y, w, h = roi
    dst = dst[y:y+h, x:x+w]

    cv2.imshow('Calibration Result', dst)
    key = cv2.waitKey(10)
    if key == ord("q"):
        break

cv2.destroyAllWindows()